### ISSUE TITLE
Object [object Object] has no method 'on'

### ISSUE THREAD

**Issue by DanielApt** [xdissent/karma-ievms#10]
I'm trying to set up some automated tests with Karma, and want to run tests against my IE VMs.

Currently it's very basic, with only one test checking if `true` equals `true`.

Even in this very basic scenario it fails with the following error:

```
TypeError: Object [object Object] has no method 'on'
    at /Users/danielapt/Desktop/auto-tests/node_modules/karma/lib/launcher.js:95:17
    at next (/Users/danielapt/Desktop/auto-tests/node_modules/karma/node_modules/batch/index.js:118:7)
    at Batch.end (/Users/danielapt/Desktop/auto-tests/node_modules/karma/node_modules/batch/index.js:154:5)
    at launch (/Users/danielapt/Desktop/auto-tests/node_modules/karma/lib/launcher.js:111:11)
    at invoke (/Users/danielapt/Desktop/auto-tests/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/Users/danielapt/Desktop/auto-tests/node_modules/karma/lib/server.js:171:24)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1056:10
    at process._tickCallback (node.js:448:13)
```

The `on` that seems to not exist is defined inside `karma's` [launcher.js:96](https://github.com/karma-runner/karma/blob/master/lib/launcher.js#L96)

What should I do? I _do_ notice the VM being opened, but nothing seems to happen once it has been opened. Please let me know if you need any further info.

**Comment by niksy** [comment]
Having the same error:

``` sh
TypeError: browser.on is not a function
    at /Users/niksy/Projects/karma-test/node_modules/karma/lib/launcher.js:95:17
    at next (/Users/niksy/Projects/karma-test/node_modules/karma/node_modules/batch/index.js:118:7)
    at Batch.end (/Users/niksy/Projects/karma-test/node_modules/karma/node_modules/batch/index.js:154:5)
    at launch (/Users/niksy/Projects/karma-test/node_modules/karma/lib/launcher.js:111:11)
    at invoke (/Users/niksy/Projects/karma-test/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/Users/niksy/Projects/karma-test/node_modules/karma/lib/server.js:171:24)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1262:10)
    at nextTickCallbackWith1Arg (node.js:426:9)
    at process._tickCallback (node.js:348:17)
```

**Comment by DanielApt** [comment]
@xdissent Looks like it's not just me, and has been verified by another user. I believe this issue is now worth addressing. 

If there's anything I can do to help, please let me know.

**Comment by hbeaufils** [comment]
Same thing for me using Karma 0.13.22

**Comment by lucasfcosta** [comment]
This is happening to me too

**Comment by mjbradford89** [comment]
Getting the same issue on Karma 0.13.2

**Comment by jhuesos** [comment]
The project hasn't been updated for a year.... I am not holding my breath for a fix :(

**Comment by niksy** [comment]
@DanielApt @hbeaufils @lucasfcosta @mjbradford89 @jhuesos If anyone’s interested, I’ve managed to get it working: https://github.com/niksy/karma-ievms/tree/browser-decorator

Since I don’t know CoffeeScript, I’ve fixed it in transpiled code, so if anyone want’s to transfer it to CoffeeScript and make PR to main repo, fire away :)

What was the problem? I was looking at already existing launchers and saw that all those launchers inherit `baseBrowserDecorator` which has all necessary lifecycle methods. That decorator is available if you inject default arguments. After that, everything was working mostly OK, but there was also `forceKill` method missing so I added that which just calls `kill` method and waits for it’s return signal (`Promise`).

Also, methods can’t be defined on prototype, but must be initiated on every instance creation.

Also, I’ve taken time to implement default logger so you can get terminal output of different VM lifecycle events (open VM, close and stop VM).

Hope it helps you!

**Comment by guillaumevincent** [comment]
@niksy this works and fix the error for me :

```
npm install 'git+https://github.com/niksy/karma-ievms.git#browser-decorator' --save-dev
```

**Comment by markfeimer** [comment]
@niksy Thanks for the fix, it works like a charm!
